### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by cmckni3** [immense/knockout-datatable#17]
It would be nice to have some automated tests. We can use something like [mocha](https://github.com/mochajs/mocha) along with [karma](https://github.com/karma-runner/karma) and [karma-mocha](https://github.com/karma-runner/karma-mocha).

**Comment by cbankester** [comment]
[Mocha.js](http://mochajs.org/) + [Karma.js](http://karma-runner.github.io/0.12/index.html) + [karma-mocha](https://github.com/karma-runner/karma-mocha) + Selenium (or some other functional testing driver)
