### ISSUE TITLE
Supplying an observableArray as rows breaks filtering

### ISSUE THREAD

**Issue by sandermvanvliet** [immense/knockout-datatable#32]
In the various examples the rows supplied to the DataTable call are just standard array's, however when I supply an observableArray instead at first glance everything seems to work just fine (rows will display, sorting works) however when try to filter the result is always an empty list.

Currently I've done a quick and dirty fix to replace this.rows with the observableArray that is supplied and that seems to do the trick:
```javascript
this.rows(rows)
```
changed to:
```javascript
if(ko.isObservable(rows) && 'push' in rows) {
   this.rows = rows;
} else {
   this.rows(rows);
}
```

I'm curious if I may have missed something or if there is another way to solve this particular problem.

**Comment by cbankester** [comment]
@sandermvanvliet Instead of passing an observableArray, you should use the `addRecord`, `removeRecord` and `replaceRows` methods defined on DataTable instances. For instance, if you wanted to have the datatable mirror an observableArray, you could do something like:
```js
var rowObservable = ko.observableArray(...);
var options = {...};
var table = new DataTable(rowObservable(), options);
rowObservable.subscribe(function(newVal){
  table.replaceRows(newVal);
};
```

Honestly, though, you should just cut out the observable all-together and instead integrate the `addRecord` and `removeRecord` methods into the lifetime of your view model. For instance, assume you have a view model `UserIndex` which represents a list of User records, and a method `deleteUser` defined on that view model. You could define the method like so:

```js
UserIndex.prototype.deleteUser = function(user){
  // send a delete request to the server or something.
  table.removeRecord(user);
};
```

**Comment by sandermvanvliet** [comment]
Thanks for the feedback, that indeed makes life easier.
Is there a way to bulk add a list of new items a la replaceRows?

**Comment by cbankester** [comment]
There's not an `addRecords` method, though I suppose that would be a great convenience. You could do something like this, though:
```javascript
table.replaceRows(table.rows().concat(new_rows));
```

**Comment by NerijusV** [comment]
@cbankester, I am using your proposed solution with `subscribe` event where `replaceRows` is called. I have noticed that then data observable array is changed (and `replaceRows` is called), table in the view shows `No Data` row for a short time. It is a bit annoying sometimes.
For example, my code looks like this (it is TypeScript, but I hope there is no problem):
```
this.DataList.subscribe((newValue: model.PayerActionInfo[]) => { this.ModelDataTable.replaceRows(newValue); }); //my data observable array
...
this.ModelDataTable.loading(true); //show 'loading' in Data Table
$.ajax({....})
	.done((resp: any) => {
		this.DataList($.map(resp.PayerActionListResult, (el, i) => {
			return new model.PayerActionInfo(el);
		}));		
		this.ModelDataTable.loading(false);
	})
	.fail((d, textStatus, error) => {
		this.ModelDataTable.loading(false);
		...
	});
```

and user sees this sequence:
1. "Loading..."
2. "No Data" for a very short time
3. Normal Results

Is it normal behavior of the data table and nothing can be done about it? Or my code is wrong?

**Comment by cbankester** [comment]
@NerijusV That is very interesting. I just tested it with several thousand rows and I wasn't able to reproduce it, but it's totally within the realm of possibility that there's something amiss with how we're handling the `rows` observable within the code.

What does your "No Data" binding look like? Is it possible your binding is responding to some other event that's triggered by the changing rows?

Also, make sure you're not calling `this.ModelDataTable.replaceRows` with an empty array anywhere before you're calling it from within your Ajax callback.
