### ISSUE TITLE
pager is too long

### ISSUE THREAD

**Issue by anhuisunfei** [immense/knockout-datatable#40]
For example, I have 1000 record, pager bar will be very long

**Comment by cmbankester** [comment]
@anhuisunfei You can specify your own pager to use. For instance,

```html
<div class="pagination" data-bind="visible: pages() > 1">
  <ul>
    <li data-bind="css: leftPagerClass, click: prevPage">
      <a href="#">&laquo;</a>
    </li>
    <li data-bind="visible: pages() > 2">&hellip;</li>
    <li data-bind="css: rightPagerClass, click: nextPage">
      <a href="#">&raquo;</a>
    </li>
  </ul>
</div>
```
would display the previous page and next page links, and <code>&hellip;</code> in the middle.

**Comment by cmckni3** [comment]
@cmbankester Think we should add that to the example folder?

**Comment by cmbankester** [comment]
Yeah, that would make sense. I mean, we should test it first, but yeah.

**Comment by cmckni3** [comment]
Agreed
